// Auto-generated decision tree header for 8051 (Keil C)
// Generated by gas_drift_to_8051.py

#ifndef DT_MODEL_H
#define DT_MODEL_H

#include <stdint.h>

// Node index of root
#define TREE_ROOT (0)
// Total nodes
#define TREE_SIZE (15)
// Leaf marker in tree_feature[]
#define TREE_LEAF (-2)

static const int16_t tree_feature[TREE_SIZE] = {
  16, 4, -2, 9, 0, 1, -2, -2, 0, -2, -2, -2, 16, -2, -2
};

static const uint8_t tree_threshold[TREE_SIZE] = {
  153, 2, 0, 6, 84, 158, 0, 0, 222, 0, 0, 0, 162, 0, 0
};

static const int16_t tree_children_left[TREE_SIZE] = {
  1, 2, -1, 4, 5, 6, -1, -1, 9, -1, -1, -1, 13, -1, -1
};

static const int16_t tree_children_right[TREE_SIZE] = {
  12, 3, -1, 11, 8, 7, -1, -1, 10, -1, -1, -1, 14, -1, -1
};

static const float tree_values[TREE_SIZE] = {
  0.019658, 0.000000, 0.000000, 0.000000, 0.000000, 0.000000, 0.000000, 0.000000, 0.000000, 0.000000, 0.000000, 0.000000, 0.968750, 0.875000, 1.000000
};

// Per-feature min/max used for 0..255 quantization
#define N_FEATURES (17)
static const float feature_min[N_FEATURES] = { 0.000000, 27.000000, 2023.000000, 0.005000, 0.006000, 0.028000, 0.011000, 0.004000, 0.002000, 0.003000, 0.023000, 0.019000, 0.064000, 0.024000, 0.048000, 0.056000, 0.001015 };
static const float feature_max[N_FEATURES] = { 2102.000000, 52.000000, 2023.000000, 3.649000, 14.182000, 3.219000, 1.249000, 0.367000, 0.897000, 6.983000, 1.847000, 5.723000, 3.329000, 1.270000, 2.890000, 5.922000, 0.546356 };

#endif // DT_MODEL_H
